### PR TITLE
Refactor mcmcmonitor reducer

### PR DESCRIPTION
**Pull request by jsoules**
This PR comprises two major and one minor change.

The major changes are:

- Complete test coverage now in place for `MCMCMonitorData` and corresponding reducer, as well as the `updateSequences` file/function.
- Reducer refactored to move sequence update logic into the reducer rather than having it reside in separate files.

A corresponding minor change was:
- Refactoring the location of type definitions, so type definitions for the client-side cache (`MCMCMonitorData` etc) are in their own file separate from the processing logic, and have their own typeguards;
- Adding an `index.js` to the type definitions directory in the `service` project to simplify imports;
- Updating import statements throughout the code to handle these two changes.

To comment further on the reducer-logic refactor:

- In the previous version of the code, updating the data for the cached sequences was something of a delicate dance between the reducer and the (async) function `updateSequences` (in [src/MCMCMonitorDataManager/updateSequences.ts](https://github.com/flatironinstitute/mcmc-monitor/blob/main/src/MCMCMonitorDataManager/updateSequences.ts)). At sequence update time, this function called reducer actions to update the set of known sequences to include all those implied by the selected variable names/chain IDs/run ID; then make an API request to get updated information for them; then iterate over the results to append new data to the main cache and mark any received result as updated. This logic was difficult to follow and involved repeated updates to the main cache from an asynchronous function that could easily be called multiple times in parallel.
- The refactor makes the following changes:
  - The `"setSelectedVariableNames"`, `"setSelectedChainIds"`, and `"setSelectedRunId"` reducer verbs now have responsibility for ensuring that the cache's list of sequences includes every combination implied by the selections. That is, updating `MCMCMonitor.sequences[]` to include every `runId/chainId/variableName` combination happens as those selections are made rather than waiting for updates to be requested.
  - This significantly reduces the length of the `updateSequences` function, which can now just query the state cache for sequences in need of update, then make an (async) API request with those values.
  - The logic for actually updating the sequences (using the API request results) has also been moved into the reducer, which can handle this synchronously and in atomic batch. This keeps the update logic closer to the data and also further simplifies the `updateSequences` function. I also expect (but can't demonstrate) that it reduces the risk of race conditions, since asynchronous (and potentially out of order) requests to the reducer are restricted to (presumably serialized) requests to process API responses, as opposed to the potential case where one update function flags a particular sequence as updated during the time that another instance is constructing its API request, etc.

Something similar might be doable with running the updated statistics for the chain-sequences and variables, but that's more inherently asynchronous since it's computationally expensive and thus done by a web worker, so I'm not going to touch it right now.

Deployed this branch to dev at https://flatironinstitute.github.io/mcmc-monitor/dev/?s=https://lit-bayou-76056.herokuapp.com

### CODE REVIEW

**Comment by magland** [comment]
@jsoules This indeed looks simpler. If you've tested it and it works, then I'm in favor of merging and deploying.

**Comment by jsoules** [comment]
Just did one more rebase, given the changes we pushed to main earlier.

I've re-deployed to dev at https://flatironinstitute.github.io/mcmc-monitor/dev/?s=https://lit-bayou-76056.herokuapp.com and will click around on that a bit more just to be absolutely sure.

**Comment by magland** [comment]
Seems to work, although you should probably test it while live updating.

**Comment by jsoules** [comment]
Tested while live updating--everything still appears to function as expected. So I'm going to go ahead and merge this & publish.

**Pull request merged**
