### PR TITLE
Add popover explainer for scatterplots options.

### LINKED ISSUE #91: scatterplots vs scatterplots matrix
From Bob:

>> What's the difference between scatterplots and scatterplots matrix?
>> For me, it just changes sizes.

I guess we should make this more clear.

### PR DESCRIPTION
**Pull request by jsoules**
Fix #91.

Adds an info icon which, when clicked, pops up a small text explaining what the scatterplot options mean.

Originally I was going to use a direct tooltip, but the `react-tooltip` module seemed a little finicky. In particular, the tooltip was always getting hidden by the graphs if any graphs were displayed (regardless of what I did with the z-index).

### CODE REVIEW

**Comment by magland** [comment]
@jsoules When you have a chance could you deploy this to dev folder so I can see it in action? Or if you are confident it is not breaking anything, you can go ahead and merge (the code looks fine to me).

**Comment by jsoules** [comment]
> When you have a chance could you deploy this to dev folder so I can see it in action?

Sure thing! I've deployed and it should be up as soon as github-pages refreshes.

**Comment by magland** [comment]
Looks great!

**Comment by jsoules** [comment]
Sounds good! I'll get that merged & published.

**Pull request merged**
