### PR TITLE
Separate acf, histogram tabs

### LINKED ISSUE #63: Separate autocorrelation functions and histograms into their own tabs from main view
Per Andrew G on 5/8.

### PR DESCRIPTION
**Pull request by jsoules**
Fixes #63.

This PR addresses that issue by creating two new tabs in the run-page for plots of histograms and autocorrelation function outputs (respectively). That part is pretty straightforward cut-and-paste code movement, however, I did several rounds of subsequent refactoring to fix the resulting redundant code and to break out reused pieces into (hopefully) more obvious locations. More can still be done in that regard, but I think I got the worst of it managed.

In the process, I removed the "display [variable graphs | acfs | histograms]" checkboxes from the diagnostics tab and the two new tabs, since each of those now show only one type of data. I left a lot of that plumbing in place so that it can be adapted to a checkbox that will control whether the warmup draws are included in the displayed data (see issue #62).

I also did a little light housecleaning by adding a directory for tabs (as distinct from other components).

### CODE REVIEW

**Comment by jsoules** [comment]
Oh, deployed these changes to dev preview at https://flatironinstitute.github.io/mcmc-monitor/dev/?s=https://lit-bayou-76056.herokuapp.com#/run/multi-normal-1

**Comment by magland** [comment]
I think it looks good. Fine by me to merge as is. I do wonder whether the "Diagnostics" tab should be renamed.

**Comment by jsoules** [comment]
> I do wonder whether the "Diagnostics" tab should be renamed.

Yeah, I was wondering about that... wasn't sure what to call it though. At this point it's variable plots; but "Plots" doesn't seem like a very compelling name...

**Comment by magland** [comment]
Maybe "Timeseries"

**Comment by jsoules** [comment]
Updated to Time Series.

**Comment by magland** [comment]
I'd say this is ready to be deployed... I have some more examples I'd like to share, but I'll wait for these latest updates to be incorporated into prod.

**Comment by jsoules** [comment]
Just merged and pushed this, so it's now live. (Or, will be in a couple minutes when github-pages updates.)

**Comment by jsoules** [comment]
Okay, something choked the first time, but I just redeployed and can confirm the new tab layout is now live. Enjoy!

**Pull request merged**
